# Generated by Django 3.2 on 2023-04-18 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaverequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='from_hour',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='to_hour',
            field=models.TimeField(blank=True),
        ),
    ]
