# Generated by Django 3.2 on 2023-04-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequests', '0003_auto_20230418_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
