# Generated by Django 3.2 on 2023-04-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequests', '0004_alter_leaverequest_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='details',
            field=models.TextField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
