# Generated by Django 3.2 on 2023-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_confirmationcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='value',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
