# Generated by Django 3.2 on 2023-04-23 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_confirmationcode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_codes', to='companies.company'),
        ),
    ]
