# Generated by Django 3.2 on 2023-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_confirmationcode_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
