# Generated by Django 3.2 on 2023-04-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20230418_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='balance',
            field=models.FloatField(default=208),
        ),
    ]
